### ISSUE TITLE
terraform module setup fails on anonymous download

### ISSUE THREAD

**Issue by next-jesusmanuelnavarro** [jmnavarrol/bash-magic-enviro#6]
While trying to make BME work on a docker container I found terraform module fails on setup:
```sh
        WARNING: 'tfenv' repository not found: cloning it.
Cloning into '/home/XXXXXX/.bme.d/tfenv'...
Warning: Permanently added the ECDSA host key for IP address '140.82.121.3' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
        ERROR: While cloning repository (see above): 'git@github.com:tfutils/tfenv.git' ('v3.0.0').
        INFO: 'TFENV_TERRAFORM_VERSION' environment variable is not set.  Setting it to 'min-required' by default.
        ERROR: 'terraform-support' not loaded. See missed dependencies above.
```

From the logs it seems it's trying to git clone 'git@github.com:tfutils/tfenv.git' ('v3.0.0') but there aren't credentials within the container to sucess on that.  Given tfenv is meant to be used as *"read-only"*, I don't think there's a need to download it by means of `git@github...` when `https://github.com...` would suffice without identity requirements.

**Comment by jmnavarrol** [comment]
It seems there's no undesirable side-effects on just cloning from https instead of git@, so that's all I did.

Closed on v1.4.5.
