### ISSUE TITLE
Add ability for relocation to Makefile

### ISSUE THREAD

**Issue by next-jesusmanuelnavarro** [jmnavarrol/bash-magic-enviro#7]
While trying to install BME on a container I wanted to install it in a global fashion, i.e.: either under /usr/local/bin/ or maybe under /opt/ but I found current Makefile didn't support that.

I think it would be a nice addition.

**Comment by jmnavarrol** [comment]
Version **v1.4.5** adds the ability to install to a different directory by means of DESTDIR var to make.  I.e.: `make DESTDIR=/opt/bme install`.

**Comment by jmnavarrol** [comment]
I helped myself using a docker container; cleaning and publishing it will be a matter of a future release (see [TODO](../blob/main/TODO.md)).

For now, I close this issue.
