### ISSUE TITLE
.bme_files seem to be loaded in the wrong order

### ISSUE THREAD

**Issue by next-jesusmanuelnavarro** [jmnavarrol/bash-magic-enviro#9]
As per docs, "jumping" into a deep subdirectory loads three files:
1. the main .bme_configuration at the project's  root.
1. the .bme_env file at the project's root.
1. the .bme_env file at the destination directory.

My tests show there's something wrong with the loading logic: my project loads different virtualenvs at root, at a mid path and at a deep one.  Jumping right into the deepest path ends up with a virtualenv which is only activated neither at the root path nor at the destination path but on the middle one even if activating debug doesn't show trace about that middle .bme_env file being evaluated.

**Comment by jmnavarrol** [comment]
I can't reproduce the bug on a test project, with or without virtualenvs activation.

**Comment by next-jesusmanuelnavarro** [comment]
> I can't reproduce the bug on a test project, with or without virtualenvs activation.

Me neither.  Maybe I got confused by some pre-dependencies on my environment.  I think this can be closed.

If I manage to reproduce the bug, I'll try to produce better evidences.
